# Generated by Django 5.2.1 on 2025-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('STUDY', '공부중'), ('PHONE', '딴짓'), ('AWAY', '이석')], default='STUDY', max_length=10),
        ),
    ]
